"""initial schema

Revision ID: a5413306bd0d
Revises: 
Create Date: 2026-09-09 11:56:13.848950

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a5413306bd0d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('investigations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('input_identifier', sa.Text(), nullable=False),
    sa.Column('identifier_type', sa.String(length=20), nullable=False),
    sa.Column('normalized_identifier', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('technical_metadata', sa.JSON(), nullable=False),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_normalized_identifier'), 'investigations', ['normalized_identifier'], unique=False)
    op.create_table('source_health',
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('installed', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('timeout_count', sa.Integer(), nullable=False),
    sa.Column('total_duration_seconds', sa.Float(), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('source_name')
    )
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_explanation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'entity_type', 'normalized_value', name='uq_entity_fingerprint')
    )
    op.create_index(op.f('ix_entities_investigation_id'), 'entities', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_entities_normalized_value'), 'entities', ['normalized_value'], unique=False)
    op.create_table('search_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_jobs_investigation_id'), 'search_jobs', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_search_jobs_source_name'), 'search_jobs', ['source_name'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('source_entity_id', sa.String(length=36), nullable=False),
    sa.Column('target_entity_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'source_entity_id', 'target_entity_id', 'relationship_type', name='uq_relationship_fingerprint')
    )
    op.create_index(op.f('ix_entity_relationships_investigation_id'), 'entity_relationships', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_source_entity_id'), 'entity_relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_target_entity_id'), 'entity_relationships', ['target_entity_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('relationship_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['search_jobs.id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['entity_relationships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_entity_id'), 'evidence', ['entity_id'], unique=False)
    op.create_index(op.f('ix_evidence_investigation_id'), 'evidence', ['investigation_id'], unique=False)
    op.create_table('pivots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('parent_entity_id', sa.String(length=36), nullable=False),
    sa.Column('pivot_entity_id', sa.String(length=36), nullable=True),
    sa.Column('triggering_evidence_id', sa.String(length=36), nullable=True),
    sa.Column('identifier_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('job_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['parent_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['pivot_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['triggering_evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pivots_investigation_id'), 'pivots', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_pivots_normalized_value'), 'pivots', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_pivots_parent_entity_id'), 'pivots', ['parent_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pivots_parent_entity_id'), table_name='pivots')
    op.drop_index(op.f('ix_pivots_normalized_value'), table_name='pivots')
    op.drop_index(op.f('ix_pivots_investigation_id'), table_name='pivots')
    op.drop_table('pivots')
    op.drop_index(op.f('ix_evidence_investigation_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_entity_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_entity_relationships_target_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_source_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_investigation_id'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_search_jobs_source_name'), table_name='search_jobs')
    op.drop_index(op.f('ix_search_jobs_investigation_id'), table_name='search_jobs')
    op.drop_table('search_jobs')
    op.drop_index(op.f('ix_entities_normalized_value'), table_name='entities')
    op.drop_index(op.f('ix_entities_investigation_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_investigations_normalized_identifier'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
