"""queue leases idempotency audit rate limit

Revision ID: f5892256a9ab
Revises: a5413306bd0d
Create Date: 2026-09-09 11:58:34.898093

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f5892256a9ab'
down_revision: str | Sequence[str] | None = 'a5413306bd0d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('api_key_id', sa.String(length=36), nullable=True),
    sa.Column('client_name', sa.String(length=100), nullable=True),
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_api_key_id'), 'audit_log', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_audit_log_investigation_id'), 'audit_log', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('rate_limit_buckets',
    sa.Column('api_key_id', sa.String(length=36), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('api_key_id', 'window_start')
    )
    op.add_column('investigations', sa.Column('locked_by', sa.String(length=20), nullable=True))
    op.add_column('investigations', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('investigations', sa.Column('api_key_id', sa.String(length=36), nullable=True))
    op.add_column('investigations', sa.Column('idempotency_scope', sa.String(length=40), nullable=True))
    op.add_column('investigations', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.add_column('investigations', sa.Column('request_fingerprint', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_investigation_idempotency', 'investigations', ['idempotency_scope', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_investigation_idempotency', 'investigations', type_='unique')
    op.drop_column('investigations', 'request_fingerprint')
    op.drop_column('investigations', 'idempotency_key')
    op.drop_column('investigations', 'idempotency_scope')
    op.drop_column('investigations', 'api_key_id')
    op.drop_column('investigations', 'lease_expires_at')
    op.drop_column('investigations', 'locked_by')
    op.drop_table('rate_limit_buckets')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_investigation_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_api_key_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
