"""Programmatically walk the unified app's registered routes (not docs) and
emit the Service | Original Endpoint | Unified Endpoint | Method table for
docs/UNIFIED_API_ENDPOINTS.md. Run with the unified_api venv.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from starlette.routing import Mount, Route  # noqa: E402

from app.main import SUB_APPS, app  # noqa: E402

NAMES = {
    "/scrape": "Bluweb",
    "/osint": "OSINT",
    "/reddit": "reddit_server",
    "/telegram": "telegram_poc",
}

rows: list[tuple[str, str, str, str]] = []


def walk(routes, mount_prefix: str, base_prefix: str, service: str) -> None:
    for r in routes:
        kind = type(r).__name__
        if kind == "_IncludedRouter":
            child_prefix = base_prefix + r.include_context.prefix
            walk(r.original_router.routes, mount_prefix, child_prefix, service)
        elif isinstance(r, Mount):
            walk(r.routes, mount_prefix, base_prefix + r.path, service)
        elif isinstance(r, Route):
            original = base_prefix + r.path
            unified = mount_prefix + original
            methods = sorted(m for m in (r.methods or []) if m != "HEAD")
            for method in methods:
                rows.append((service, original, unified, method))


for route in app.routes:
    if not isinstance(route, Mount):
        continue
    prefix = route.path
    service = NAMES.get(prefix, prefix)
    sub_app = SUB_APPS[prefix]
    walk(sub_app.router.routes, prefix, "", service)

rows.sort(key=lambda r: (r[0], r[1], r[3]))

with open(Path(__file__).resolve().parent.parent / "docs" / "UNIFIED_API_ENDPOINTS.md", "w") as f:
    f.write("# Unified API — Endpoint Inventory (generated from live registered routes)\n\n")
    f.write(
        "Generated by walking `app.routes` on the actual running unified FastAPI "
        "instance (`unified_api/gen_endpoint_table.py`), not from documentation — "
        "per Milestone 3 Step 1. Total routes: "
        f"{len(rows)}.\n\n"
    )
    f.write("| Service | Original Endpoint | Unified Endpoint | Method |\n")
    f.write("|---|---|---|---|\n")
    for service, original, unified, method in rows:
        f.write(f"| {service} | `{original}` | `{unified}` | {method} |\n")

print(f"wrote {len(rows)} rows")
per_service: dict[str, int] = {}
for service, *_ in rows:
    per_service[service] = per_service.get(service, 0) + 1
for k, v in per_service.items():
    print(f"  {k}: {v}")
