#!/usr/bin/env bash
# One-time (idempotent) native SearxNG install -- no Docker. Clones SearxNG
# from source into ./searxng-src, installs it into its own venv, and writes
# a local settings.yml (limiter disabled -- no Redis/Valkey needed for a
# single-user local instance, JSON output enabled, a curated engine subset
# enabled -- see app/search_client.py's docstring for why).
#
# Verified against SearxNG 2026.9.8 on Python 3.12; project requires >=3.10.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_DIR="$ROOT_DIR/searxng-src"

if [ ! -d "$SRC_DIR" ]; then
    echo "Cloning searxng..."
    git clone --depth 1 https://github.com/searxng/searxng "$SRC_DIR"
fi

if [ ! -d "$SRC_DIR/venv" ]; then
    echo "Creating venv..."
    python3 -m venv "$SRC_DIR/venv"
fi

# shellcheck disable=SC1091
source "$SRC_DIR/venv/bin/activate"
pip install -U pip setuptools wheel pyyaml msgspec typing-extensions pybind11 -q
pip install --use-pep517 --no-build-isolation -e "$SRC_DIR" -q
deactivate

if [ ! -f "$SRC_DIR/settings.yml" ]; then
    echo "Writing local settings.yml (limiter disabled, JSON enabled)..."
    SECRET="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
    cat > "$SRC_DIR/settings.yml" <<EOF
# Local, no-Docker SearxNG instance for the OSINT platform. Generated by
# scripts/setup_searxng.sh -- edit freely, this file is not overwritten on
# re-run.
use_default_settings: true

general:
  debug: false
  instance_name: "osint-local-searxng"

search:
  safe_search: 0
  autocomplete: ''
  formats:
    - html
    - json

server:
  secret_key: "$SECRET"
  limiter: false
  image_proxy: true
  port: 8890
  bind_address: "127.0.0.1"

# bing/mojeek/google are disabled upstream by default -- enabled here to
# evaluate; see scripts/verify_searxng_engines.py for which actually return
# results without CAPTCHA/parsing failures when self-hosted.
engines:
  - name: bing
    disabled: false
  - name: mojeek
    disabled: false
  - name: google
    disabled: false
  - name: wikipedia
    display_type: ["infobox", "list"]
EOF
fi

echo "Done. Start with: ./scripts/start_searxng.sh"
