"""sources monitoring tables

Revision ID: 5c37aa88e121
Revises: 0002
Create Date: 2026-09-04 16:02:12.223025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('preflight_id', sa.UUID(), nullable=True),
    sa.Column('crawl_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('max_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('current_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('consecutive_unchanged_crawls', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_crawl_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_crawl_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['preflight_id'], ['preflight_reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_domain'), 'sources', ['domain'], unique=False)
    op.create_index(op.f('ix_sources_next_crawl_at'), 'sources', ['next_crawl_at'], unique=False)
    op.create_index(op.f('ix_sources_normalized_url'), 'sources', ['normalized_url'], unique=True)
    op.create_index(op.f('ix_sources_status'), 'sources', ['status'], unique=False)
    op.create_table('monitoring_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('previous_version', sa.Integer(), nullable=True),
    sa.Column('new_version', sa.Integer(), nullable=True),
    sa.Column('change_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_events_detected_at'), 'monitoring_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_monitoring_events_document_id'), 'monitoring_events', ['document_id'], unique=False)
    op.create_index(op.f('ix_monitoring_events_source_id'), 'monitoring_events', ['source_id'], unique=False)
    op.create_table('source_urls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_urls_normalized_url'), 'source_urls', ['normalized_url'], unique=False)
    op.create_index(op.f('ix_source_urls_source_id'), 'source_urls', ['source_id'], unique=False)
    op.create_foreign_key(None, 'crawl_jobs', 'sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'sources', ['source_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'crawl_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_source_urls_source_id'), table_name='source_urls')
    op.drop_index(op.f('ix_source_urls_normalized_url'), table_name='source_urls')
    op.drop_table('source_urls')
    op.drop_index(op.f('ix_monitoring_events_source_id'), table_name='monitoring_events')
    op.drop_index(op.f('ix_monitoring_events_document_id'), table_name='monitoring_events')
    op.drop_index(op.f('ix_monitoring_events_detected_at'), table_name='monitoring_events')
    op.drop_table('monitoring_events')
    op.drop_index(op.f('ix_sources_status'), table_name='sources')
    op.drop_index(op.f('ix_sources_normalized_url'), table_name='sources')
    op.drop_index(op.f('ix_sources_next_crawl_at'), table_name='sources')
    op.drop_index(op.f('ix_sources_domain'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
