"""document current_content for search

Revision ID: f0722687f4a1
Revises: 0003
Create Date: 2026-09-04 16:05:09.503741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (none pre-phase-3, but this
    # migration must be safe against a table that already has documents).
    op.add_column(
        'documents', sa.Column('current_content', sa.Text(), nullable=False, server_default='')
    )
    op.alter_column('documents', 'current_content', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'current_content')
    # ### end Alembic commands ###
