"""domain profile and failure classification

Revision ID: 734cf37e8bd9
Revises: 0004
Create Date: 2026-09-04 17:05:19.211501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills any existing rows, then gets dropped so future
    # inserts go through the ORM defaults instead (same pattern as 0004).
    op.add_column(
        'fetch_strategy_stats', sa.Column('avg_content_bytes', sa.Float(), nullable=False, server_default='0')
    )
    op.alter_column('fetch_strategy_stats', 'avg_content_bytes', server_default=None)
    op.add_column(
        'fetch_strategy_stats',
        sa.Column('failure_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'),
    )
    op.alter_column('fetch_strategy_stats', 'failure_counts', server_default=None)
    op.add_column('source_urls', sa.Column('last_failure_category', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_urls', 'last_failure_category')
    op.drop_column('fetch_strategy_stats', 'failure_counts')
    op.drop_column('fetch_strategy_stats', 'avg_content_bytes')
    # ### end Alembic commands ###
