"""document page_type classification

Revision ID: 40131cc0a21a
Revises: 0005
Create Date: 2026-09-04 17:11:23.516121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('page_type', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_documents_page_type'), 'documents', ['page_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_page_type'), table_name='documents')
    op.drop_column('documents', 'page_type')
    # ### end Alembic commands ###
