"""domain profile learning and url pattern stats

Revision ID: eec3e3ca4406
Revises: 0007
Create Date: 2026-09-04 17:25:44.176281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _add_column_with_backfill(table: str, column: sa.Column, default_sql: str) -> None:
    """Add as nullable, backfill existing rows via UPDATE, then tighten to
    NOT NULL -- the standard safe pattern for adding a required column to a
    table that already has rows (setting `server_default=` on the Column
    object after construction doesn't reliably reach the DDL compiler, so
    this drives it explicitly instead)."""
    was_nullable = column.nullable
    column.nullable = True
    op.add_column(table, column)
    op.execute(f"UPDATE {table} SET {column.name} = {default_sql} WHERE {column.name} IS NULL")
    if not was_nullable:
        op.alter_column(table, column.name, nullable=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_pattern_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('page_type', sa.String(length=32), nullable=True),
    sa.Column('fetch_attempts', sa.Integer(), nullable=False),
    sa.Column('successful_fetches', sa.Integer(), nullable=False),
    sa.Column('extraction_attempts', sa.Integer(), nullable=False),
    sa.Column('extraction_successes', sa.Integer(), nullable=False),
    sa.Column('http_attempts', sa.Integer(), nullable=False),
    sa.Column('http_successes', sa.Integer(), nullable=False),
    sa.Column('browser_attempts', sa.Integer(), nullable=False),
    sa.Column('browser_successes', sa.Integer(), nullable=False),
    sa.Column('preferred_strategy', sa.String(length=16), nullable=True),
    sa.Column('preferred_extractor', sa.String(length=32), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('avg_content_bytes', sa.Float(), nullable=False),
    sa.Column('failure_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', 'pattern', 'page_type', name='uq_url_pattern_stats_domain_pattern_type')
    )
    op.create_index(op.f('ix_url_pattern_stats_domain'), 'url_pattern_stats', ['domain'], unique=False)
    _add_column_with_backfill(
        'fetch_strategy_stats', sa.Column('success_status_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False), "'{}'::jsonb"
    )
    _add_column_with_backfill('fetch_strategy_stats', sa.Column('js_required_count', sa.Integer(), nullable=False), '0')
    _add_column_with_backfill('fetch_strategy_stats', sa.Column('empty_content_count', sa.Integer(), nullable=False), '0')
    op.add_column('fetch_strategy_stats', sa.Column('preferred_extractor', sa.String(length=32), nullable=True))
    _add_column_with_backfill('fetch_strategy_stats', sa.Column('crawl_delay_ms', sa.Float(), nullable=False), '0')
    _add_column_with_backfill('fetch_strategy_stats', sa.Column('recommended_concurrency', sa.Integer(), nullable=False), '5')
    _add_column_with_backfill('fetch_strategy_stats', sa.Column('circuit_state', sa.String(length=16), nullable=False), "'healthy'")
    op.add_column('fetch_strategy_stats', sa.Column('circuit_opened_at', sa.DateTime(timezone=True), nullable=True))
    _add_column_with_backfill('fetch_strategy_stats', sa.Column('consecutive_failures', sa.Integer(), nullable=False), '0')
    op.add_column('fetch_strategy_stats', sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fetch_strategy_stats', 'last_observed_at')
    op.drop_column('fetch_strategy_stats', 'consecutive_failures')
    op.drop_column('fetch_strategy_stats', 'circuit_opened_at')
    op.drop_column('fetch_strategy_stats', 'circuit_state')
    op.drop_column('fetch_strategy_stats', 'recommended_concurrency')
    op.drop_column('fetch_strategy_stats', 'crawl_delay_ms')
    op.drop_column('fetch_strategy_stats', 'preferred_extractor')
    op.drop_column('fetch_strategy_stats', 'empty_content_count')
    op.drop_column('fetch_strategy_stats', 'js_required_count')
    op.drop_column('fetch_strategy_stats', 'success_status_counts')
    op.drop_index(op.f('ix_url_pattern_stats_domain'), table_name='url_pattern_stats')
    op.drop_table('url_pattern_stats')
    # ### end Alembic commands ###
