"""document_changes

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-04 18:14:33.636196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0009'
down_revision: Union[str, None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('previous_version_id', sa.UUID(), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('page_type', sa.String(length=32), nullable=True),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('change_confidence', sa.Float(), nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_version_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_changes_change_type'), 'document_changes', ['change_type'], unique=False)
    op.create_index(op.f('ix_document_changes_created_at'), 'document_changes', ['created_at'], unique=False)
    op.create_index('ix_document_changes_document_created', 'document_changes', ['document_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_document_changes_document_id'), 'document_changes', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_changes_page_type'), 'document_changes', ['page_type'], unique=False)
    op.create_index(op.f('ix_document_changes_severity'), 'document_changes', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_changes_severity'), table_name='document_changes')
    op.drop_index(op.f('ix_document_changes_page_type'), table_name='document_changes')
    op.drop_index(op.f('ix_document_changes_document_id'), table_name='document_changes')
    op.drop_index('ix_document_changes_document_created', table_name='document_changes')
    op.drop_index(op.f('ix_document_changes_created_at'), table_name='document_changes')
    op.drop_index(op.f('ix_document_changes_change_type'), table_name='document_changes')
    op.drop_table('document_changes')
    # ### end Alembic commands ###
