"""phase8_entity_story_intelligence

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-05 00:18:10.692941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0010'
down_revision: Union[str, None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pg_trgm (spec Phase 8 section 34): trigram similarity support for
    # entity-alias fuzzy candidate lookup. entity_resolver.py's own fuzzy
    # matching runs in Python (RapidFuzz) against a bounded per-type
    # candidate set for this phase; the GIN trgm index below is added now
    # so a future SQL-side `normalized_name % 'query'` candidate filter
    # (avoiding the Python-side full per-type fetch entirely) is a query
    # change, not a schema migration.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'normalized_name', name='uq_entity_type_normalized_name')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index('ix_entities_normalized_name', 'entities', ['normalized_name'], unique=False)
    op.create_index(
        'ix_entities_normalized_name_trgm', 'entities', ['normalized_name'],
        unique=False, postgresql_using='gin', postgresql_ops={'normalized_name': 'gin_trgm_ops'},
    )
    op.create_table('entity_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('alias_text', sa.Text(), nullable=False),
    sa.Column('normalized_alias', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'normalized_alias', name='uq_entity_alias_entity_normalized')
    )
    op.create_index(op.f('ix_entity_aliases_entity_id'), 'entity_aliases', ['entity_id'], unique=False)
    op.create_index('ix_entity_aliases_normalized_alias', 'entity_aliases', ['normalized_alias'], unique=False)
    op.create_table('entity_mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extractor', sa.String(length=32), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'entity_id', 'start_offset', name='uq_entity_mention_doc_entity_offset')
    )
    op.create_index('ix_entity_mentions_document_id', 'entity_mentions', ['document_id'], unique=False)
    op.create_index('ix_entity_mentions_entity_id', 'entity_mentions', ['entity_id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_title', sa.Text(), nullable=True),
    sa.Column('representative_document_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('scoring_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['representative_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stories_last_activity_at', 'stories', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_stories_status'), 'stories', ['status'], unique=False)
    op.create_table('story_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_method', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('feature_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matching_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scoring_version', sa.String(length=16), nullable=False),
    sa.Column('attached_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'document_id', name='uq_story_document')
    )
    op.create_index('ix_story_documents_document_id', 'story_documents', ['document_id'], unique=False)
    op.create_index('ix_story_documents_story_id', 'story_documents', ['story_id'], unique=False)
    op.create_table('story_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'entity_id', name='uq_story_entity')
    )
    op.create_index('ix_story_entities_entity_id', 'story_entities', ['entity_id'], unique=False)
    op.create_index('ix_story_entities_story_id', 'story_entities', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_story_entities_story_id', table_name='story_entities')
    op.drop_index('ix_story_entities_entity_id', table_name='story_entities')
    op.drop_table('story_entities')
    op.drop_index('ix_story_documents_story_id', table_name='story_documents')
    op.drop_index('ix_story_documents_document_id', table_name='story_documents')
    op.drop_table('story_documents')
    op.drop_index(op.f('ix_stories_status'), table_name='stories')
    op.drop_index('ix_stories_last_activity_at', table_name='stories')
    op.drop_table('stories')
    op.drop_index('ix_entity_mentions_entity_id', table_name='entity_mentions')
    op.drop_index('ix_entity_mentions_document_id', table_name='entity_mentions')
    op.drop_table('entity_mentions')
    op.drop_index('ix_entity_aliases_normalized_alias', table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_entity_id'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index('ix_entities_normalized_name_trgm', table_name='entities')
    op.drop_index('ix_entities_normalized_name', table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
